### ISSUE TITLE
Failed to launch checking. For more information, see the Troubleshooting guide. Data Structures / Tuples

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/introduction_to_python#115]
Failed to launch checking. For more information, see the Troubleshooting guide
Failed to launch checking. For more information, see the Troubleshooting guide

**Comment by sofiiako** [comment]
Cannot reproduce this. Please do check out the Troubleshooting guide. If it does not help, please let us know what issues you encountered. Thank you!
