### ISSUE TITLE
my solution is identical as given answer but fails Modules and Packages / Executing modules as scripts

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/introduction_to_python#119]
My answer to the problem is identical as a given solution. When I 'peek at the solution' is says 'contents are identical'. Yet 'check' fails.
True is not false : You should move the last print statement in some_module into the `main` block.

**Comment by sofiiako** [comment]
Hi! In this task, you need to edit two files, not just task.py but also some_module.py

To see the diff with the solution for multiple files, after clicking "Peek solution", use the navigation arrows at the top of the editor view.
<img width="1039" alt="Screenshot 2022-07-20 at 19 40 36" src="https://user-images.githubusercontent.com/5954159/180047355-513dec4d-088d-4893-90ae-9da933518beb.png">
