### ISSUE TITLE
failed to launch checking Strings / String Length

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/introduction_to_python#132]
does not check. in the tasks before this check, they passed without problems
Failed to launch checking. For more information, see the Troubleshooting guide

**Comment by sofiiako** [comment]
Hi! Please refer to the [troubleshooting guide](https://plugins.jetbrains.com/plugin/10081-edutools/docs/troubleshooting-guide.html#no_tests_have_run).
