### ISSUE TITLE
Clicking "Next" breaks the UI.  Variables / Undefined Variable - Not just this one

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/introduction_to_python#148]
Before clicking "Next", I can interact with the Editor. Right click context menu and insert '|' prompt available for interaction. After clicking "Next", these two (at the very least) interface elements stop working. At first I thought that the .py file had become read-only. I'm not completely sure this isn't the case. No error messages are generated. I've tried watching the text output to the launch terminal, and examining the logs. I haven't been able to identify what the particular error is. 

It is momentarily fixed by  using: File -> Repair IDE -> Recovery step 3: 'Reopen Project' ". Doing this restores editor interaction... until 'Next' is clicked again. 100% reproducible. 

I'm hoping someone can provide suggestions on how to better diagnose the issue.
I've checked for the Run tool window, but it isn't visible in my IDE. Where your illustration shows

"Version Control,   >Run,   =TODO, ... etc."

mine shows

"Version Control,   Python Packages,  =TODO, ... etc."

**Comment by igalimov** [comment]
It appears to be a known issue that was recently fixed: https://youtrack.jetbrains.com/issue/EDU-5489/.
The fix will be included in the next EduTools plugin update.

As a temporary workaround, switch the task description to Swing in **Help | Find Action | Switch Task Description Panel**.
