### ISSUE TITLE
Expected answer is incorrect Modules and Packages / Built-in modules

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/introduction_to_python#187]
The assignment says to print the current date but the expected answer requires a specially formatted datetime
Lists differ: ['2023-04-27 14','05'] != ['2023-04-27']

**Comment by sofiiako** [comment]
Hi! The task asks to "Print the current date and time using an imported built-in module datetime."
and there's a hint that says "Use the datetime.datetime.today() function."
