### ISSUE TITLE
My answer wont be accepted even though its correct

### ISSUE THREAD

**Issue by epeltz33** [jetbrains-academy/introduction_to_python#193]
Inside the Functions section under the Definition folder in functions.py, I keep getting an incorrect response when I press the check button but my code is correct. I am not sure why this is happening.  I will attach a screenshot below: 

![Screenshot 2023-05-29 at 8 53 23 PM](https://github.com/jetbrains-academy/introduction_to_python/assets/86162368/d831de7d-8536-49e3-83b5-321074ea8d7f)

**Comment by Geravant** [comment]
Hello, @epeltz33 ! Could you please check what version of the JetBrains Academy plugin you use?

**Comment by epeltz33** [comment]
Hey, @Geravant I am using version 2023.5 - 2023.1-646 I believe.

**Comment by epeltz33** [comment]
I uninstalled PyCharm and reinstalled it and that seemed to do the trick. For some reason the pytests were not being found by the interpretor and I think that is what the issue was.  Thanks!
