### ISSUE TITLE
failed to launch checking (python) Loops / For Loop

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/introduction_to_python#202]
run tool shows correct solution, but still an error. learning tool won't check submission 
Traceback (most recent call last):
  File "/home/jay/PycharmProjects/Introduction to Python/Loops/For loop/for_loop.py", line 8, in <module>
    print(primes[x])
IndexError: list index out of range

**Comment by DaniilBogdanovJB** [comment]
Can't reproduce:
![image](https://github.com/jetbrains-academy/introduction_to_python/assets/121797687/e0014832-15b0-4ca3-839c-8feb923a7603)
