### ISSUE TITLE
This is the only answer I cannot check Strings / String Slicing

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/introduction_to_python#203]
I haven't had any problems checking the answers for other tests. I'm not sure why this one is not working for me.
TypeError: type 'str' is not subscriptable

**Comment by sofiiako** [comment]
The error you mentioned might have arisen because you might have tried to slice a single character as if it were a string collection. To avoid the error and achieve the intended result, you should use slicing notation as described in the task.
