### ISSUE TITLE
Spelling issue Introduction / Task Description

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/introduction_to_python#204]
Run your code (for a theoretical tasks)

Should be either:

Run your code (for a theoretical task)

Or:

Run your code (for theoretical tasks)

**Comment by sofiiako** [comment]
Already fixed here https://github.com/jetbrains-academy/introduction_to_python/commit/bc39e5efa3e960b3059f2c0ddd719c1514cdb77a
