### ISSUE TITLE
Incorrect code Variables / Arithmetic Operators

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/introduction_to_python#210]
The task says to "Calculate a remainder of such a division", so in line 5, shouldn't we find a remainder of a variable "division_result" rather than "number"?

**Comment by sofiiako** [comment]
Hi! No, this line of the task asks to calculate the remainder of the same division calculated on line 3. It says "Divide the value stored in 'number' by 2. Calculate a remainder of such a division."
