### ISSUE TITLE
Example is not correct Data Structures / Join Method

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/introduction_to_python#216]
Python is a programing language is not the correct output
"Python is a programming is a language" is the correct output

**Comment by kochaika** [comment]
Hi!
Thank you for your feedback.

In the example, `list_` have **two** elements (strings)
```
list_ = ['Python', 'programming language']
```
So `sep.join(list_)` will joint **two** elements. 
This is equivalent to: `'Python' + ' is a ' + 'programming language'`

So, there is no error here.
