### ISSUE TITLE
Wrong operator in boolean_order.py

### ISSUE THREAD

**Issue by anetri** [jetbrains-academy/introduction_to_python#28]
There is an operator "is" used incorrectly on line 8 of Condition expressions/Boolean operators order/boolean_order.py:
print(name is "Ellis" or not (name is "John" and age == 17))

there should be operator ==

**Comment by sofiiako** [comment]
Thank you for your feedback! 
The task will be changed once this update is merged: https://github.com/jetbrains-academy/introduction_to_python/pull/29
