### ISSUE TITLE
My code is exactly the same Functions / Definition

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/introduction_to_python#67]
My code is exactly the same yet when I press check it says error.

**Comment by Geravant** [comment]
Unfortunately, can't really reproduce this. 
I get the "Error" message while misspelling the function name though, instead of the testing system response. I'll look into the message being displayed by the checker.

**Comment by sofiiako** [comment]
@Geravant can we close this issue?

**Comment by Geravant** [comment]
@sofiiako , yes, please
